In [ ]:
from google.colab import drive
drive.mount("/content/drive")

In [ ]:
%cd /content

!rm -rf colab
!git clone https://github.com/sihasi/colab.git

%cd colab

!uv pip install --system -r requirements-colab.txt
!uv pip install --system -e .

In [ ]:
import pathlib
import pandas as pd
import polars as pl


def find_project_root(start: pathlib.Path | None = None) -> pathlib.Path:
    start = (start or pathlib.Path.cwd()).resolve()
    for path in (start, *start.parents):
        if (path / "data").exists():
            return path
    raise FileNotFoundError("Could not find project root containing data/")


datadir = "/content/drive/data/estyle"

pd_hotel       = pd.read_parquet(datadir / "hotel.parquet")
pd_customer    = pd.read_parquet(datadir / "customer.parquet")
pd_reservation = pd.read_parquet(datadir / "reservation.parquet")

pl_hotel       = pl.read_parquet(datadir / "hotel.parquet")
pl_customer    = pl.read_parquet(datadir / "customer.parquet")
pl_reservation = pl.read_parquet(datadir / "reservation.parquet")

In [3]:
df = pd.DataFrame({
    'col1': [1, 2, 3, 4],
    'col2': [5, 6, 7, 8],
    'col3': ['a', 'b', 'a', 'b'],
})

df.max()

col1    4
col2    8
col3    b
dtype: object

In [4]:
df = pl.DataFrame({
    'col1': [1, 2, 3, 4],
    'col2': [5, 6, 7, 8],
    'col3': ['a', 'b', 'a', 'b'],
})

expr = pl.col("*").max() # Expression
df.select(expr) # Expressionを用いて処理

shape: (1, 3)
┌──────┬──────┬──────┐
│ col1 ┆ col2 ┆ col3 │
│ ---  ┆ ---  ┆ ---  │
│ i64  ┆ i64  ┆ str  │
╞══════╪══════╪══════╡
│ 4    ┆ 8    ┆ b    │
└──────┴──────┴──────┘

In [5]:
# 列名で指定して列を選択
pd_reservation[[
    "reservation_id",
    "hotel_id",
    "customer_id",
    "checkin_date",
    "checkout_date",
]]

,reservation_id,hotel_id,customer_id,checkin_date,checkout_date
0,1,2460,53431,2014-12-31 00:00:00+09:00,2015-01-03 00:00:00+09:00
1,2,962,488390,2014-12-31 00:00:00+09:00,2015-01-02 00:00:00+09:00
2,3,558,341335,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00
3,4,3666,398981,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00
4,5,2180,220381,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00
...,...,...,...,...,...
1999995,1999996,2357,280303,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00
1999996,1999997,319,499387,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00
1999997,1999998,2834,461799,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00
1999998,1999999,3643,163568,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00
1999999,2000000,820,449765,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00

In [6]:
# 列名で指定して列を選択
pl_reservation.select(
    pl.col([
        "reservation_id",
        "hotel_id",
        "customer_id",
        "checkin_date",
        "checkout_date",
    ])
)

shape: (2_000_000, 5)
┌────────────────┬──────────┬─────────────┬──────────────────────────┬──────────────────────────┐
│ reservation_id ┆ hotel_id ┆ customer_id ┆ checkin_date             ┆ checkout_date            │
│ ---            ┆ ---      ┆ ---         ┆ ---                      ┆ ---                      │
│ i64            ┆ i64      ┆ i64         ┆ datetime[ns, Asia/Tokyo] ┆ datetime[ns, Asia/Tokyo] │
╞════════════════╪══════════╪═════════════╪══════════════════════════╪══════════════════════════╡
│ 1              ┆ 2460     ┆ 53431       ┆ 2014-12-31 00:00:00 JST  ┆ 2015-01-03 00:00:00 JST  │
│ 2              ┆ 962      ┆ 488390      ┆ 2014-12-31 00:00:00 JST  ┆ 2015-01-02 00:00:00 JST  │
│ 3              ┆ 558      ┆ 341335      ┆ 2014-12-31 00:00:00 JST  ┆ 2015-01-01 00:00:00 JST  │
│ 4              ┆ 3666     ┆ 398981      ┆ 2014-12-31 00:00:00 JST  ┆ 2015-01-01 00:00:00 JST  │
│ 5              ┆ 2180     ┆ 220381      ┆ 2014-12-31 00:00:00 JST  ┆ 2015-01-01 00:00:00 JST  │
│ …              ┆ …        ┆ …           ┆ …                        ┆ …                        │
│ 1999996        ┆ 2357     ┆ 280303      ┆ 2019-12-29 00:00:00 JST  ┆ 2019-12-30 00:00:00 JST  │
│ 1999997        ┆ 319      ┆ 499387      ┆ 2019-12-29 00:00:00 JST  ┆ 2019-12-30 00:00:00 JST  │
│ 1999998        ┆ 2834     ┆ 461799      ┆ 2019-12-30 00:00:00 JST  ┆ 2019-12-31 00:00:00 JST  │
│ 1999999        ┆ 3643     ┆ 163568      ┆ 2019-12-30 00:00:00 JST  ┆ 2019-12-31 00:00:00 JST  │
│ 2000000        ┆ 820      ┆ 449765      ┆ 2019-12-30 00:00:00 JST  ┆ 2019-12-31 00:00:00 JST  │
└────────────────┴──────────┴─────────────┴──────────────────────────┴──────────────────────────┘

In [7]:
cols = [
    "reservation_id",
    "hotel_id",
    "customer_id",
    "checkin_date",
    "checkout_date",
]

pd_reservation[cols]

,reservation_id,hotel_id,customer_id,checkin_date,checkout_date
0,1,2460,53431,2014-12-31 00:00:00+09:00,2015-01-03 00:00:00+09:00
1,2,962,488390,2014-12-31 00:00:00+09:00,2015-01-02 00:00:00+09:00
2,3,558,341335,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00
3,4,3666,398981,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00
4,5,2180,220381,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00
...,...,...,...,...,...
1999995,1999996,2357,280303,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00
1999996,1999997,319,499387,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00
1999997,1999998,2834,461799,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00
1999998,1999999,3643,163568,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00
1999999,2000000,820,449765,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00

In [8]:
[col for col in cols if col not in ('reservation_id')]

['hotel_id', 'customer_id', 'checkin_date', 'checkout_date']

In [9]:
# people_numが2から4の範囲の行を抽出
pd_reservation.query("2 <= people_num <= 4")

,reservation_id,hotel_id,customer_id,reserved_at,checkin_date,checkout_date,length_of_stay,people_num,total_price,status,canceled_at
0,1,2460,53431,2013-12-31 07:00:14+09:00,2014-12-31 00:00:00+09:00,2015-01-03 00:00:00+09:00,3,2,37800,reserved,NaT
1,2,962,488390,2013-12-31 08:23:35+09:00,2014-12-31 00:00:00+09:00,2015-01-02 00:00:00+09:00,2,3,42000,reserved,NaT
2,3,558,341335,2013-12-31 09:02:05+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,2,20400,reserved,NaT
3,4,3666,398981,2013-12-31 23:44:54+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,4,39600,reserved,NaT
4,5,2180,220381,2014-01-01 02:47:50+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,3,16500,reserved,NaT
...,...,...,...,...,...,...,...,...,...,...,...
1999989,1999990,4850,4121,2019-12-26 19:24:22+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,2,12200,reserved,NaT
1999990,1999991,3655,405333,2019-12-26 19:38:18+09:00,2019-12-28 00:00:00+09:00,2019-12-31 00:00:00+09:00,3,4,165600,reserved,NaT
1999992,1999993,2988,381053,2019-12-26 23:02:15+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,4,40800,reserved,NaT
1999994,1999995,658,445219,2019-12-27 06:47:33+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,3,18300,reserved,NaT
1999995,1999996,2357,280303,2019-12-27 12:14:07+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,4,26000,reserved,NaT

In [10]:
# people_numが2から4の範囲の行を抽出
pd_reservation.loc[lambda df: df.people_num.between(2, 4)]

,reservation_id,hotel_id,customer_id,reserved_at,checkin_date,checkout_date,length_of_stay,people_num,total_price,status,canceled_at
0,1,2460,53431,2013-12-31 07:00:14+09:00,2014-12-31 00:00:00+09:00,2015-01-03 00:00:00+09:00,3,2,37800,reserved,NaT
1,2,962,488390,2013-12-31 08:23:35+09:00,2014-12-31 00:00:00+09:00,2015-01-02 00:00:00+09:00,2,3,42000,reserved,NaT
2,3,558,341335,2013-12-31 09:02:05+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,2,20400,reserved,NaT
3,4,3666,398981,2013-12-31 23:44:54+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,4,39600,reserved,NaT
4,5,2180,220381,2014-01-01 02:47:50+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,3,16500,reserved,NaT
...,...,...,...,...,...,...,...,...,...,...,...
1999989,1999990,4850,4121,2019-12-26 19:24:22+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,2,12200,reserved,NaT
1999990,1999991,3655,405333,2019-12-26 19:38:18+09:00,2019-12-28 00:00:00+09:00,2019-12-31 00:00:00+09:00,3,4,165600,reserved,NaT
1999992,1999993,2988,381053,2019-12-26 23:02:15+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,4,40800,reserved,NaT
1999994,1999995,658,445219,2019-12-27 06:47:33+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,3,18300,reserved,NaT
1999995,1999996,2357,280303,2019-12-27 12:14:07+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,4,26000,reserved,NaT

In [11]:
# people_numが2から4の範囲の行を抽出
pl_reservation.filter(pl.col("people_num").is_between(2, 4))

shape: (1_199_977, 11)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ reservatio ┆ hotel_id ┆ customer_ ┆ reserved_ ┆ … ┆ people_nu ┆ total_pri ┆ status   ┆ canceled_ │
│ n_id       ┆ ---      ┆ id        ┆ at        ┆   ┆ m         ┆ ce        ┆ ---      ┆ at        │
│ ---        ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ ---       │
│ i64        ┆          ┆ i64       ┆ datetime[ ┆   ┆ i64       ┆ i64       ┆          ┆ datetime[ │
│            ┆          ┆           ┆ ns, Asia/ ┆   ┆           ┆           ┆          ┆ ns, Asia/ │
│            ┆          ┆           ┆ Tokyo]    ┆   ┆           ┆           ┆          ┆ Tokyo]    │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 1          ┆ 2460     ┆ 53431     ┆ 2013-12-3 ┆ … ┆ 2         ┆ 37800     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 07:00:14  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 2          ┆ 962      ┆ 488390    ┆ 2013-12-3 ┆ … ┆ 3         ┆ 42000     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 08:23:35  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 3          ┆ 558      ┆ 341335    ┆ 2013-12-3 ┆ … ┆ 2         ┆ 20400     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 09:02:05  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 4          ┆ 3666     ┆ 398981    ┆ 2013-12-3 ┆ … ┆ 4         ┆ 39600     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 23:44:54  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 5          ┆ 2180     ┆ 220381    ┆ 2014-01-0 ┆ … ┆ 3         ┆ 16500     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 02:47:50  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ …          ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ 1999990    ┆ 4850     ┆ 4121      ┆ 2019-12-2 ┆ … ┆ 2         ┆ 12200     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 19:24:22  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 1999991    ┆ 3655     ┆ 405333    ┆ 2019-12-2 ┆ … ┆ 4         ┆ 165600    ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 19:38:18  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 1999993    ┆ 2988     ┆ 381053    ┆ 2019-12-2 ┆ … ┆ 4         ┆ 40800     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 23:02:15  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 1999995    ┆ 658      ┆ 445219    ┆ 2019-12-2 ┆ … ┆ 3         ┆ 18300     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 7         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 06:47:33  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 1999996    ┆ 2357     ┆ 280303    ┆ 2019-12-2 ┆ … ┆ 4         ┆ 26000     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 7         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 12:14:07  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [12]:
pd_reservation.total_price.mean()

np.float64(40029.4968)

In [13]:
# 1%にサンプリングしてtotal_priceの平均を計算（元データの平均は40029.4968）
(
    pd_reservation
    .sample(frac=0.01, random_state=71)
    .total_price.mean()
)

np.float64(39769.37)

In [14]:
# 1%にサンプリングしてtotal_priceの平均を計算（元データの平均は40029.4968）
(
    pl_reservation
    .sample(fraction=0.01, seed=71)
    .select(pl.col("total_price").mean())
)

shape: (1, 1)
┌─────────────┐
│ total_price │
│ ---         │
│ f64         │
╞═════════════╡
│ 40481.29    │
└─────────────┘

In [15]:
(
    pd_reservation
    .groupby("customer_id").size()
    .mean()
)

np.float64(4.791934216327078)

In [16]:
(
    pd_reservation
    .sample(frac=0.01, random_state=71)
    .groupby("customer_id").size()
    .mean()
)

np.float64(1.0281190561867064)

In [17]:
(
    pd_reservation
    # （1）顧客をサンプリングし、サンプリングした顧客の予約を抽出
    .loc[lambda df:
        df.customer_id.isin(
            pd.Series(df.customer_id.unique())
            .sample(frac=0.01, random_state=71)
        )
    ]
    # （2）顧客毎に予約数をカウントし、平均を計算
    .groupby("customer_id").size()
    .mean()
)

np.float64(4.760900814566363)

In [18]:
(
    pl_reservation
    # （1）顧客をサンプリングし、サンプリングした顧客の予約を抽出
    .filter(
        pl.col("customer_id").is_in(
            pl.col("customer_id")
            .unique()
            .sample(fraction=0.01, seed=71)
            .implode()
        )
    )
    # （2）顧客毎に予約数をカウントし、平均を計算
    .group_by("customer_id").len()
    .select(pl.col("len").mean())
)

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ f64      │
╞══════════╡
│ 4.852864 │
└──────────┘

In [19]:
(
    pl_reservation
    # （1）顧客をサンプリングし、サンプリングした顧客の予約を抽出
    .select(
        pl.col("customer_id")
        .unique()
        .sample(fraction=0.01, seed=71)
        .implode()
    )
)

shape: (1, 1)
┌────────────────────────────┐
│ customer_id                │
│ ---                        │
│ list[i64]                  │
╞════════════════════════════╡
│ [121773, 209920, … 319578] │
└────────────────────────────┘

In [20]:
# キャンセルを除いたホテルごとの売上を集計
(
    pd_reservation
    # （1）キャンセル済みではない予約の抽出
    .query("status != 'canceled'")
    # （2）hotel_idの値ごとにtotal_priceの総和を計算
    .groupby("hotel_id").total_price.sum()
)

hotel_id
1       19631800
3       48453000
4        9555000
5       14004000
6       14137200
          ...
4996    36529900
4997    11545600
4998    26674300
4999    55862400
5000     9965000
Name: total_price, Length: 4527, dtype: int64

In [21]:
# キャンセルを除いたホテルごとの売上を集計
(
    pl_reservation
    # （1）キャンセル済みではない予約の抽出
    .filter(pl.col("status") != "canceled")
    # （2）hotel_idの値ごとにtotal_priceの総和を計算
    .group_by("hotel_id").agg(pl.col("total_price").sum())
)

shape: (4_527, 2)
┌──────────┬─────────────┐
│ hotel_id ┆ total_price │
│ ---      ┆ ---         │
│ i64      ┆ i64         │
╞══════════╪═════════════╡
│ 1206     ┆ 1586100     │
│ 4996     ┆ 36529900    │
│ 4082     ┆ 23512500    │
│ 3811     ┆ 14902200    │
│ 4326     ┆ 17870500    │
│ …        ┆ …           │
│ 2971     ┆ 30597600    │
│ 1807     ┆ 16838700    │
│ 1021     ┆ 5165600     │
│ 1670     ┆ 10932600    │
│ 3665     ┆ 6110300     │
└──────────┴─────────────┘

In [22]:
(
    pd_reservation
    # （1）キャンセル済みではない予約の抽出
    .query("status != 'canceled'")
    # （2）集計値の計算
    .groupby("hotel_id")
    .agg(
        cnt=("reservation_id", "count"),
        sales=("total_price", "sum"),
        mean_sales=("total_price", "mean"),
    )
)

          cnt     sales     mean_sales
hotel_id
1         484  19631800   40561.570248
3         661  48453000   73302.571861
4         493   9555000   19381.338742
5         401  14004000   34922.693267
6         511  14137200   27665.753425
...       ...       ...            ...
4996      763  36529900   47876.671035
4997      339  11545600   34057.817109
4998      401  26674300   66519.451372
4999      497  55862400  112399.195171
5000      490   9965000   20336.734694

[4527 rows x 3 columns]

In [23]:
(
    pl_reservation
    # （1）キャンセル済みではない予約の抽出
    .filter(pl.col("status") != "canceled")
    # （2）集計値の計算
    .group_by("hotel_id")
    .agg([
        pl.col("reservation_id").len().alias("cnt"),
        pl.col("total_price").sum().alias("sales"),
        pl.col("total_price").mean().alias("mean_sales"),
    ])
)

shape: (4_527, 4)
┌──────────┬─────┬──────────┬──────────────┐
│ hotel_id ┆ cnt ┆ sales    ┆ mean_sales   │
│ ---      ┆ --- ┆ ---      ┆ ---          │
│ i64      ┆ u32 ┆ i64      ┆ f64          │
╞══════════╪═════╪══════════╪══════════════╡
│ 572      ┆ 291 ┆ 10377400 ┆ 35661.168385 │
│ 3025     ┆ 640 ┆ 21197000 ┆ 33120.3125   │
│ 4588     ┆ 277 ┆ 8336600  ┆ 30096.028881 │
│ 3290     ┆ 435 ┆ 27679200 ┆ 63630.344828 │
│ 682      ┆ 62  ┆ 1306800  ┆ 21077.419355 │
│ …        ┆ …   ┆ …        ┆ …            │
│ 780      ┆ 206 ┆ 3500200  ┆ 16991.262136 │
│ 3254     ┆ 70  ┆ 1537800  ┆ 21968.571429 │
│ 2057     ┆ 217 ┆ 7196900  ┆ 33165.437788 │
│ 116      ┆ 232 ┆ 5394000  ┆ 23250.0      │
│ 762      ┆ 275 ┆ 12237900 ┆ 44501.454545 │
└──────────┴─────┴──────────┴──────────────┘

In [24]:
pd_null = pd.DataFrame({
    "category": ["A", "A", "B", "B", "C"],
    "values": [10, None, 30, None, 50]
})
(
    pd_null
    .groupby("category")
    .agg(
        min_value=("values", "min"),
        sum_value=("values", "sum"),
        count_value=("values", "count"),
        size_value=("values", "size"),
    )
)

          min_value  sum_value  count_value  size_value
category
A              10.0       10.0            1           2
B              30.0       30.0            1           2
C              50.0       50.0            1           1

In [25]:
pl_null = pl.DataFrame({
    "category": ["A", "A", "B", "B", "C"],
    "values": [10, None, 30, None, 50]
})
(
    pl_null
    .group_by("category")
    .agg([
        pl.col("values").min().alias("min_value"),
        pl.col("values").sum().alias("sum_value"),
        pl.col("values").count().alias("count_value"),
        pl.col("values").len().alias("len_value"),
    ])
)

shape: (3, 5)
┌──────────┬───────────┬───────────┬─────────────┬───────────┐
│ category ┆ min_value ┆ sum_value ┆ count_value ┆ len_value │
│ ---      ┆ ---       ┆ ---       ┆ ---         ┆ ---       │
│ str      ┆ i64       ┆ i64       ┆ u32         ┆ u32       │
╞══════════╪═══════════╪═══════════╪═════════════╪═══════════╡
│ A        ┆ 10        ┆ 10        ┆ 1           ┆ 2         │
│ B        ┆ 30        ┆ 30        ┆ 1           ┆ 2         │
│ C        ┆ 50        ┆ 50        ┆ 1           ┆ 1         │
└──────────┴───────────┴───────────┴─────────────┴───────────┘

In [26]:
df1 = pd_reservation.query("status != 'canceled'")
df2 = df1.groupby("hotel_id").total_price.sum()
display(df1)
display(df2)

,reservation_id,hotel_id,customer_id,reserved_at,checkin_date,checkout_date,length_of_stay,people_num,total_price,status,canceled_at
0,1,2460,53431,2013-12-31 07:00:14+09:00,2014-12-31 00:00:00+09:00,2015-01-03 00:00:00+09:00,3,2,37800,reserved,NaT
1,2,962,488390,2013-12-31 08:23:35+09:00,2014-12-31 00:00:00+09:00,2015-01-02 00:00:00+09:00,2,3,42000,reserved,NaT
2,3,558,341335,2013-12-31 09:02:05+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,2,20400,reserved,NaT
3,4,3666,398981,2013-12-31 23:44:54+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,4,39600,reserved,NaT
4,5,2180,220381,2014-01-01 02:47:50+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,3,16500,reserved,NaT
...,...,...,...,...,...,...,...,...,...,...,...
1999994,1999995,658,445219,2019-12-27 06:47:33+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,3,18300,reserved,NaT
1999995,1999996,2357,280303,2019-12-27 12:14:07+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,4,26000,reserved,NaT
1999997,1999998,2834,461799,2019-12-28 04:59:51+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,5,105000,reserved,NaT
1999998,1999999,3643,163568,2019-12-28 11:56:19+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,1,17000,reserved,NaT
1999999,2000000,820,449765,2019-12-28 17:20:08+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,1,7800,reserved,NaT

hotel_id
1       19631800
3       48453000
4        9555000
5       14004000
6       14137200
          ...
4996    36529900
4997    11545600
4998    26674300
4999    55862400
5000     9965000
Name: total_price, Length: 4527, dtype: int64

In [27]:
import numpy as np

(
    pd_hotel
    # （1）unit_priceを丸めた列を作成
    .assign(unit_price_range=lambda df:
        (np.floor(df.unit_price / 5000) * 5000)
        .astype(int))
    # （2）unit_price_rangeの値ごとにデータ数をカウント
    .groupby("unit_price_range").size()
)

unit_price_range
0         220
5000     2760
10000    1389
15000     456
20000     139
25000      29
30000       6
35000       1
dtype: int64

In [28]:
(
    pl_hotel
    # （1）unit_priceを丸めたものを集約キーとしてgroup_by
    .group_by(
        ((pl.col("unit_price") / 5000).floor() * 5000)
        .cast(pl.Int32)
    )
    # （2）グループごとにデータ数をカウント
    .agg(pl.len())
)

shape: (8, 2)
┌────────────┬──────┐
│ unit_price ┆ len  │
│ ---        ┆ ---  │
│ i32        ┆ u32  │
╞════════════╪══════╡
│ 0          ┆ 220  │
│ 15000      ┆ 456  │
│ 30000      ┆ 6    │
│ 5000       ┆ 2760 │
│ 20000      ┆ 139  │
│ 35000      ┆ 1    │
│ 10000      ┆ 1389 │
│ 25000      ┆ 29   │
└────────────┴──────┘

In [29]:
# DataFrameを作成
df1 = pd.DataFrame({"A": [1, 2, 3]})

# DataFrameをコピー
df2 = df1

# コピー先のDataFrameに新しい列を追加
df2["B"] = df2["A"] * 2

# 元のDataFrameを表示
df1

   A  B
0  1  2
1  2  4
2  3  6

In [30]:
# DataFrameを作成
df1 = pd.DataFrame({"A": [1, 2, 3]})

# DataFrameに新しい列を追加
df2 = (
    df1
    .assign(B=lambda df: df["A"] * 2)
)

# 元のDataFrameを表示
df1

   A
0  1
1  2
2  3

In [31]:
import numpy as np
(
    pd_hotel
    # （1）unit_priceを数値区間に丸めた列を作成
    .assign(unit_price_range=lambda df:
        np.where(df.unit_price < 5000, 0,
        np.where(df.unit_price < 10000, 5000,
        np.where(df.unit_price < 20000, 10000,
        np.where(df.unit_price < 30000, 20000,
            30000)))))
    # （2）unit_price_rangeの値ごとにデータ数をカウント
    .groupby("unit_price_range").size()
)

unit_price_range
0         220
5000     2760
10000    1845
20000     168
30000       7
dtype: int64

In [32]:
(
    pl_hotel
    # （1）unit_priceを丸めた数値区間データを作成し、それ集約キーとしてgroup by
    .group_by(
        pl.when(pl.col("unit_price") < 5000).then(0)
        .when(pl.col("unit_price") < 10000).then(5000)
        .when(pl.col("unit_price") < 20000).then(10000)
        .when(pl.col("unit_price") < 30000).then(20000)
        .otherwise(30000)
        .alias("unit_price")
    # （2）数値区間ごとにデータ数をカウント
    ).agg(pl.count())
)

/var/folders/57/jbbs3zzs09vd02vtg2w0vyg40000gn/T/ipykernel_2148/544611036.py:12: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
  ).agg(pl.count())

shape: (5, 2)
┌────────────┬───────┐
│ unit_price ┆ count │
│ ---        ┆ ---   │
│ i32        ┆ u32   │
╞════════════╪═══════╡
│ 0          ┆ 220   │
│ 30000      ┆ 7     │
│ 5000       ┆ 2760  │
│ 20000      ┆ 168   │
│ 10000      ┆ 1845  │
└────────────┴───────┘

In [33]:
(
    pd_reservation
    # （1）キャンセル済みではない予約の抽出
    .query("status != 'canceled'")
    # （2）checkout_dateを月ごとのPeriod型に変換
    .assign(month=lambda df: df.checkout_date.dt.to_period("M"))
    # （3）monthの値ごとにtotal_priceの総和を計算
    .groupby("month").total_price.sum()
)

/var/folders/57/jbbs3zzs09vd02vtg2w0vyg40000gn/T/ipykernel_2148/3039295416.py:6: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  .assign(month=lambda df: df.checkout_date.dt.to_period("M"))

month
2015-01     730844200
2015-02     650411000
2015-03    1447995200
2015-04     697578500
2015-05    2185718000
2015-06     697210900
2015-07    1465165300
2015-08    2910478200
2015-09     708236200
2015-10     733080000
2015-11     704430600
2015-12    1468389300
2016-01     730553200
2016-02     688327500
2016-03    1447950000
2016-04     695937700
2016-05    2189308100
2016-06     697594900
2016-07    1457527800
2016-08    2908152300
2016-09     697209200
2016-10     717107300
2016-11     701391700
2016-12    1465204000
2017-01     727519600
2017-02     656184700
2017-03    1440961900
2017-04     699264200
2017-05    2179041700
2017-06     701322100
2017-07    1448508800
2017-08    2934380700
2017-09     722047000
2017-10     724966800
2017-11     706726000
2017-12    1460880800
2018-01     730334300
2018-02     657539300
2018-03    1451755500
2018-04     706020700
2018-05    2201273400
2018-06     694748200
2018-07    1454922700
2018-08    2905345600
2018-09     711891500
2018-10     738280200
2018-11     709726500
2018-12    1466301400
2019-01     740233700
2019-02     646023300
2019-03    1462116000
2019-04     713238400
2019-05    2171845900
2019-06     696780000
2019-07    1462451700
2019-08    2932441800
2019-09     707822000
2019-10     733193600
2019-11     704777800
2019-12    1452259500
Freq: M, Name: total_price, dtype: int64

In [34]:
(
    pl_reservation
    # （1）キャンセル済みではない予約の抽出
    .filter(pl.col("status") != "canceled")
    # （2）checkout_dateの月部分を切り出したデータを用いてgroup by
    .group_by(pl.col("checkout_date").dt.truncate("1mo"))
    # （3）月ごとにtotal_priceの総和を計算
    .agg(pl.col("total_price").sum())
)

shape: (60, 2)
┌──────────────────────────┬─────────────┐
│ checkout_date            ┆ total_price │
│ ---                      ┆ ---         │
│ datetime[ns, Asia/Tokyo] ┆ i64         │
╞══════════════════════════╪═════════════╡
│ 2019-06-01 00:00:00 JST  ┆ 696780000   │
│ 2016-02-01 00:00:00 JST  ┆ 688327500   │
│ 2015-05-01 00:00:00 JST  ┆ 2185718000  │
│ 2015-11-01 00:00:00 JST  ┆ 704430600   │
│ 2015-08-01 00:00:00 JST  ┆ 2910478200  │
│ …                        ┆ …           │
│ 2018-12-01 00:00:00 JST  ┆ 1466301400  │
│ 2015-02-01 00:00:00 JST  ┆ 650411000   │
│ 2017-01-01 00:00:00 JST  ┆ 727519600   │
│ 2016-10-01 00:00:00 JST  ┆ 717107300   │
│ 2017-04-01 00:00:00 JST  ┆ 699264200   │
└──────────────────────────┴─────────────┘

In [35]:
(
    pd_reservation
    #（1）キャンセル済みかつcanceled_atがcheckin_dateの7日以内、の判定
    .assign(is_canceled_within_7days_to_checkin=lambda df:
        (df.status == "canceled")
        & ((df.checkin_date - df.canceled_at).dt.days <= 7)
    )
    #（2）customer_idの値ごとに、is_canceled_within_7days_to_checkinが
    # Trueとなるデータが1件以上存在するかどうかを集計
    .groupby("customer_id").is_canceled_within_7days_to_checkin.max()
)

customer_id
1         False
2         False
3         False
4         False
5         False
          ...
499996    False
499997    False
499998     True
499999    False
500000    False
Name: is_canceled_within_7days_to_checkin, Length: 417368, dtype: bool

In [36]:
(
    pl_reservation
    #（1）customer_idを集約キーとしてgroup by
    .group_by("customer_id")
    #（2）customer_idの値ごとに、キャンセル済み、かつcanceled_atが
    # checkin_dateの7日以内、というデータが1件以上存在するかどうかを集計
    .agg(
        (
            (pl.col("status") == "canceled")
            & (
                (pl.col("checkin_date") - pl.col("canceled_at"))
                .dt.total_days() <= 7
            )
        ).max()
    )
)

shape: (417_368, 2)
┌─────────────┬────────┐
│ customer_id ┆ status │
│ ---         ┆ ---    │
│ i64         ┆ bool   │
╞═════════════╪════════╡
│ 471793      ┆ false  │
│ 295067      ┆ false  │
│ 383156      ┆ true   │
│ 176050      ┆ false  │
│ 55086       ┆ false  │
│ …           ┆ …      │
│ 248389      ┆ false  │
│ 286409      ┆ false  │
│ 184261      ┆ false  │
│ 134573      ┆ false  │
│ 365795      ┆ false  │
└─────────────┴────────┘

In [37]:
(
    pd_reservation
    .groupby("customer_id")
    .apply(
        lambda x: x.sort_values("checkout_date", ascending=False).iloc[0],
        include_groups=False,
    )
    .reset_index()
)

,customer_id,reservation_id,hotel_id,reserved_at,checkin_date,checkout_date,length_of_stay,people_num,total_price,status,canceled_at
0,1,1307084,3688,2017-10-12 01:27:55+09:00,2018-08-27 00:00:00+09:00,2018-08-28 00:00:00+09:00,1,4,95200,reserved,NaT
1,2,1631355,25,2018-08-03 22:03:59+09:00,2019-01-06 00:00:00+09:00,2019-01-07 00:00:00+09:00,1,4,19200,reserved,NaT
2,3,1244458,3990,2017-08-15 21:47:02+09:00,2018-05-14 00:00:00+09:00,2018-05-15 00:00:00+09:00,1,2,14600,reserved,NaT
3,4,1724947,4189,2018-10-28 04:45:22+09:00,2019-09-09 00:00:00+09:00,2019-09-10 00:00:00+09:00,1,5,22500,reserved,NaT
4,5,1705769,2977,2018-10-10 16:27:06+09:00,2019-07-22 00:00:00+09:00,2019-07-23 00:00:00+09:00,1,1,8500,reserved,NaT
...,...,...,...,...,...,...,...,...,...,...,...
417363,499996,1027770,1589,2017-01-30 02:57:05+09:00,2017-11-16 00:00:00+09:00,2017-11-17 00:00:00+09:00,1,5,75000,reserved,NaT
417364,499997,1308721,3785,2017-10-13 12:51:17+09:00,2018-03-13 00:00:00+09:00,2018-03-14 00:00:00+09:00,1,1,7500,reserved,NaT
417365,499998,1126301,1124,2017-04-30 07:19:01+09:00,2017-05-06 00:00:00+09:00,2017-05-07 00:00:00+09:00,1,1,4900,canceled,2017-05-04 09:09:20+09:00
417366,499999,1347156,3575,2017-11-17 11:55:16+09:00,2018-09-12 00:00:00+09:00,2018-09-14 00:00:00+09:00,2,4,40000,reserved,NaT
417367,500000,1575573,2339,2018-06-14 08:42:10+09:00,2019-01-12 00:00:00+09:00,2019-01-14 00:00:00+09:00,2,3,126600,reserved,NaT

In [38]:
(
    pd_reservation
    .sort_values("checkout_date", ascending=False)
    .groupby("customer_id").head(1)
)

,reservation_id,hotel_id,customer_id,reserved_at,checkin_date,checkout_date,length_of_stay,people_num,total_price,status,canceled_at
1999999,2000000,820,449765,2019-12-28 17:20:08+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,1,7800,reserved,NaT
1976701,1976702,3748,272807,2019-08-16 10:25:26+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,3,36600,reserved,NaT
1976596,1976597,4313,468901,2019-08-16 03:31:18+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,1,7200,reserved,NaT
1976452,1976453,2113,164941,2019-08-15 18:29:53+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,3,31200,reserved,NaT
1976427,1976428,3194,71183,2019-08-15 17:01:01+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,1,8600,reserved,NaT
...,...,...,...,...,...,...,...,...,...,...,...
167456,167457,3683,358412,2014-12-05 17:00:50+09:00,2014-12-30 00:00:00+09:00,2015-01-01 00:00:00+09:00,2,1,23800,reserved,NaT
168074,168075,1038,203069,2014-12-06 06:58:58+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,3,39600,reserved,NaT
19578,19579,944,285360,2014-05-12 23:09:08+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,2,14400,reserved,NaT
125084,125085,3140,38036,2014-10-22 10:50:01+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,1,8700,reserved,NaT
58502,58503,4363,498441,2014-08-01 15:26:38+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,4,33200,reserved,NaT

In [39]:
(
    pl_reservation
    .group_by("customer_id")
    .agg(
        pl.col("checkout_date").max().alias("latest_checkout_date"),
        pl.col("reservation_id").filter(
            pl.col("checkout_date") == pl.col("checkout_date").max()
        ).first().alias("latest_reservation_id")
    )
)

shape: (417_368, 3)
┌─────────────┬──────────────────────────┬───────────────────────┐
│ customer_id ┆ latest_checkout_date     ┆ latest_reservation_id │
│ ---         ┆ ---                      ┆ ---                   │
│ i64         ┆ datetime[ns, Asia/Tokyo] ┆ i64                   │
╞═════════════╪══════════════════════════╪═══════════════════════╡
│ 498666      ┆ 2015-03-08 00:00:00 JST  ┆ 19333                 │
│ 264291      ┆ 2019-12-14 00:00:00 JST  ┆ 1909641               │
│ 378434      ┆ 2019-03-12 00:00:00 JST  ┆ 1722092               │
│ 414385      ┆ 2019-04-22 00:00:00 JST  ┆ 1713232               │
│ 204882      ┆ 2019-11-22 00:00:00 JST  ┆ 1895707               │
│ …           ┆ …                        ┆ …                     │
│ 112428      ┆ 2019-10-25 00:00:00 JST  ┆ 1898913               │
│ 233961      ┆ 2019-05-28 00:00:00 JST  ┆ 1906894               │
│ 217976      ┆ 2019-11-23 00:00:00 JST  ┆ 1915546               │
│ 281675      ┆ 2019-05-03 00:00:00 JST  ┆ 1756849               │
│ 205918      ┆ 2017-08-24 00:00:00 JST  ┆ 874619                │
└─────────────┴──────────────────────────┴───────────────────────┘

In [40]:
(
    pd_reservation
    #（1）people_numが1人のデータのみ抽出
    .query("people_num == 1")
    #（3）ビジネスホテルのみのマスタを内部結合
    .merge(
        #（2）pd_hotelからビジネスホテルの行のみ抽出
        pd_hotel
        .query("hotel_type == 'ビジネスホテル'")
        ["hotel_id"],
        on="hotel_id", how="inner"
    )
)

,reservation_id,hotel_id,customer_id,reserved_at,checkin_date,checkout_date,length_of_stay,people_num,total_price,status,canceled_at
0,72,2706,100573,2014-01-08 14:32:58+09:00,2015-01-01 00:00:00+09:00,2015-01-02 00:00:00+09:00,1,1,8400,reserved,NaT
1,176,1870,40419,2014-01-14 02:33:55+09:00,2015-01-02 00:00:00+09:00,2015-01-04 00:00:00+09:00,2,1,25200,canceled,2014-06-15 16:17:35+09:00
2,190,1801,4819,2014-01-14 13:47:22+09:00,2015-01-01 00:00:00+09:00,2015-01-02 00:00:00+09:00,1,1,5900,reserved,NaT
3,191,3422,53534,2014-01-14 14:22:49+09:00,2015-01-04 00:00:00+09:00,2015-01-05 00:00:00+09:00,1,1,8400,reserved,NaT
4,194,521,138201,2014-01-14 15:39:34+09:00,2015-01-07 00:00:00+09:00,2015-01-08 00:00:00+09:00,1,1,12100,reserved,NaT
...,...,...,...,...,...,...,...,...,...,...,...
101023,1999920,509,360612,2019-12-22 21:32:12+09:00,2019-12-24 00:00:00+09:00,2019-12-25 00:00:00+09:00,1,1,12200,reserved,NaT
101024,1999921,1856,66149,2019-12-22 21:44:59+09:00,2019-12-27 00:00:00+09:00,2019-12-28 00:00:00+09:00,1,1,19500,reserved,NaT
101025,1999932,3185,149478,2019-12-23 05:08:19+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,1,5300,reserved,NaT
101026,1999965,1908,68073,2019-12-24 22:42:50+09:00,2019-12-28 00:00:00+09:00,2019-12-29 00:00:00+09:00,1,1,12900,reserved,NaT
101027,1999999,3643,163568,2019-12-28 11:56:19+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,1,17000,reserved,NaT

In [41]:
(
    pl_reservation
    #（1）people_numが1人のデータのみ抽出
    .filter(pl.col("people_num") == 1)
    #（3）ビジネスホテルのみのマスタを内部結合
    .join(
        #（2）pl_hotelからビジネスホテルの行のみ抽出
        pl_hotel
        .filter(pl.col("hotel_type") == "ビジネスホテル")
        .select("hotel_id"),
        on="hotel_id", how="inner"
    )
)

shape: (101_028, 11)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ reservatio ┆ hotel_id ┆ customer_ ┆ reserved_ ┆ … ┆ people_nu ┆ total_pri ┆ status   ┆ canceled_ │
│ n_id       ┆ ---      ┆ id        ┆ at        ┆   ┆ m         ┆ ce        ┆ ---      ┆ at        │
│ ---        ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ ---       │
│ i64        ┆          ┆ i64       ┆ datetime[ ┆   ┆ i64       ┆ i64       ┆          ┆ datetime[ │
│            ┆          ┆           ┆ ns, Asia/ ┆   ┆           ┆           ┆          ┆ ns, Asia/ │
│            ┆          ┆           ┆ Tokyo]    ┆   ┆           ┆           ┆          ┆ Tokyo]    │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 72         ┆ 2706     ┆ 100573    ┆ 2014-01-0 ┆ … ┆ 1         ┆ 8400      ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 8         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 14:32:58  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 176        ┆ 1870     ┆ 40419     ┆ 2014-01-1 ┆ … ┆ 1         ┆ 25200     ┆ canceled ┆ 2014-06-1 │
│            ┆          ┆           ┆ 4         ┆   ┆           ┆           ┆          ┆ 5         │
│            ┆          ┆           ┆ 02:33:55  ┆   ┆           ┆           ┆          ┆ 16:17:35  │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆ JST       │
│ 190        ┆ 1801     ┆ 4819      ┆ 2014-01-1 ┆ … ┆ 1         ┆ 5900      ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 4         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 13:47:22  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 191        ┆ 3422     ┆ 53534     ┆ 2014-01-1 ┆ … ┆ 1         ┆ 8400      ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 4         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 14:22:49  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 194        ┆ 521      ┆ 138201    ┆ 2014-01-1 ┆ … ┆ 1         ┆ 12100     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 4         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 15:39:34  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ …          ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ 1999920    ┆ 509      ┆ 360612    ┆ 2019-12-2 ┆ … ┆ 1         ┆ 12200     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 2         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 21:32:12  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 1999921    ┆ 1856     ┆ 66149     ┆ 2019-12-2 ┆ … ┆ 1         ┆ 19500     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 2         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 21:44:59  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 1999932    ┆ 3185     ┆ 149478    ┆ 2019-12-2 ┆ … ┆ 1         ┆ 5300      ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 3         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 05:08:19  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 1999965    ┆ 1908     ┆ 68073     ┆ 2019-12-2 ┆ … ┆ 1         ┆ 12900     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 4         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 22:42:50  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 1999999    ┆ 3643     ┆ 163568    ┆ 2019-12-2 ┆ … ┆ 1         ┆ 17000     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 8         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 11:56:19  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [42]:
(
    pd_reservation
    .query("people_num == 1")
    .merge(
        pd_hotel
        .query("hotel_type == 'ビジネスホテル'")
        ["hotel_id"],
        on="hotel_id", how="inner",
        # 多対1結合であることを検証
        validate="m:1"
    )
)

,reservation_id,hotel_id,customer_id,reserved_at,checkin_date,checkout_date,length_of_stay,people_num,total_price,status,canceled_at
0,72,2706,100573,2014-01-08 14:32:58+09:00,2015-01-01 00:00:00+09:00,2015-01-02 00:00:00+09:00,1,1,8400,reserved,NaT
1,176,1870,40419,2014-01-14 02:33:55+09:00,2015-01-02 00:00:00+09:00,2015-01-04 00:00:00+09:00,2,1,25200,canceled,2014-06-15 16:17:35+09:00
2,190,1801,4819,2014-01-14 13:47:22+09:00,2015-01-01 00:00:00+09:00,2015-01-02 00:00:00+09:00,1,1,5900,reserved,NaT
3,191,3422,53534,2014-01-14 14:22:49+09:00,2015-01-04 00:00:00+09:00,2015-01-05 00:00:00+09:00,1,1,8400,reserved,NaT
4,194,521,138201,2014-01-14 15:39:34+09:00,2015-01-07 00:00:00+09:00,2015-01-08 00:00:00+09:00,1,1,12100,reserved,NaT
...,...,...,...,...,...,...,...,...,...,...,...
101023,1999920,509,360612,2019-12-22 21:32:12+09:00,2019-12-24 00:00:00+09:00,2019-12-25 00:00:00+09:00,1,1,12200,reserved,NaT
101024,1999921,1856,66149,2019-12-22 21:44:59+09:00,2019-12-27 00:00:00+09:00,2019-12-28 00:00:00+09:00,1,1,19500,reserved,NaT
101025,1999932,3185,149478,2019-12-23 05:08:19+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,1,5300,reserved,NaT
101026,1999965,1908,68073,2019-12-24 22:42:50+09:00,2019-12-28 00:00:00+09:00,2019-12-29 00:00:00+09:00,1,1,12900,reserved,NaT
101027,1999999,3643,163568,2019-12-28 11:56:19+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,1,17000,reserved,NaT

In [43]:
(
    pl_reservation
    .filter(pl.col("people_num") == 1)
    .join(
        pl_hotel
        .filter(pl.col("hotel_type") == "ビジネスホテル")
        .select("hotel_id"),
        on="hotel_id", how="inner",
        # 多対1結合であることを検証
        validate="m:1"
    )
)

shape: (101_028, 11)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ reservatio ┆ hotel_id ┆ customer_ ┆ reserved_ ┆ … ┆ people_nu ┆ total_pri ┆ status   ┆ canceled_ │
│ n_id       ┆ ---      ┆ id        ┆ at        ┆   ┆ m         ┆ ce        ┆ ---      ┆ at        │
│ ---        ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str      ┆ ---       │
│ i64        ┆          ┆ i64       ┆ datetime[ ┆   ┆ i64       ┆ i64       ┆          ┆ datetime[ │
│            ┆          ┆           ┆ ns, Asia/ ┆   ┆           ┆           ┆          ┆ ns, Asia/ │
│            ┆          ┆           ┆ Tokyo]    ┆   ┆           ┆           ┆          ┆ Tokyo]    │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 72         ┆ 2706     ┆ 100573    ┆ 2014-01-0 ┆ … ┆ 1         ┆ 8400      ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 8         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 14:32:58  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 176        ┆ 1870     ┆ 40419     ┆ 2014-01-1 ┆ … ┆ 1         ┆ 25200     ┆ canceled ┆ 2014-06-1 │
│            ┆          ┆           ┆ 4         ┆   ┆           ┆           ┆          ┆ 5         │
│            ┆          ┆           ┆ 02:33:55  ┆   ┆           ┆           ┆          ┆ 16:17:35  │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆ JST       │
│ 190        ┆ 1801     ┆ 4819      ┆ 2014-01-1 ┆ … ┆ 1         ┆ 5900      ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 4         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 13:47:22  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 191        ┆ 3422     ┆ 53534     ┆ 2014-01-1 ┆ … ┆ 1         ┆ 8400      ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 4         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 14:22:49  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 194        ┆ 521      ┆ 138201    ┆ 2014-01-1 ┆ … ┆ 1         ┆ 12100     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 4         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 15:39:34  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ …          ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ 1999920    ┆ 509      ┆ 360612    ┆ 2019-12-2 ┆ … ┆ 1         ┆ 12200     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 2         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 21:32:12  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 1999921    ┆ 1856     ┆ 66149     ┆ 2019-12-2 ┆ … ┆ 1         ┆ 19500     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 2         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 21:44:59  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 1999932    ┆ 3185     ┆ 149478    ┆ 2019-12-2 ┆ … ┆ 1         ┆ 5300      ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 3         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 05:08:19  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 1999965    ┆ 1908     ┆ 68073     ┆ 2019-12-2 ┆ … ┆ 1         ┆ 12900     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 4         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 22:42:50  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
│ 1999999    ┆ 3643     ┆ 163568    ┆ 2019-12-2 ┆ … ┆ 1         ┆ 17000     ┆ reserved ┆ null      │
│            ┆          ┆           ┆ 8         ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ 11:56:19  ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆           ┆          ┆           │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [44]:
(
    pd_hotel
    #（2）hotel_idをキーとして（1）の集計結果を左外部結合
    .merge(
        #（1）予約履歴から条件抽出し、ホテル毎に集約
        pd_reservation
        .query("status != 'canceled'")
        .query("checkout_date.dt.year == 2019")
        .groupby("hotel_id")
        .total_price.agg(["sum", "size"]),
        on="hotel_id", how="left"
    )
    #（3）結合されなかった行の数値を0埋め
    .fillna({"sum": 0, "size": 0})
)

,hotel_id,hotel_name,hotel_type,address_prefecture,address_city,address_town,address_zipcode,unit_price,user_rating,tag_001,...,tag_023,tag_024,tag_025,tag_026,tag_027,tag_028,tag_029,tag_030,sum,size
0,1,北飯岡ホテル,ビジネスホテル,岩手県,盛岡市,北飯岡,020-0857,10300,3.256591,0,...,<NA>,0,0,1,0,0,0,0,3017900.0,83.0
1,2,西二条南温泉ホテル,リゾートホテル,北海道,中川郡美深町,西二条南,098-2242,6800,3.453642,0,...,0,<NA>,1,0,0,0,0,0,0.0,0.0
2,3,小屋敷ペンション,民宿,青森県,黒石市,小屋敷,036-0511,18600,1.381796,<NA>,...,0,1,<NA>,<NA>,0,0,0,0,10248600.0,143.0
3,4,中後町民宿,民宿,愛知県,碧南市,中後町,447-0042,4900,2.090353,0,...,0,0,0,0,0,0,1,0,1808100.0,94.0
4,5,鵜沼台ホテル,ビジネスホテル,岐阜県,各務原市,鵜沼台,509-0121,9000,2.771490,0,...,0,0,0,1,1,1,0,0,2421000.0,73.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,田辺通旅館,旅館,愛知県,名古屋市瑞穂区,田辺通,467-0027,12100,NaN,0,...,0,0,0,0,<NA>,0,1,0,6957500.0,136.0
4996,4997,六本木温泉旅館,旅館,東京都,港区,六本木,106-8544,8800,1.499441,<NA>,...,0,0,0,0,1,0,0,0,1663200.0,57.0
4997,4998,丸山吉野町温泉旅館,旅館,福岡県,北九州市門司区,丸山吉野町,801-0824,15700,2.336651,0,...,0,0,1,0,0,0,<NA>,1,5275200.0,81.0
4998,4999,神埼郡吉野ヶ里町ビジネスホテル,ビジネスホテル,佐賀県,神埼郡吉野ヶ里町,<NA>,842-0000,25300,1.559659,<NA>,...,<NA>,0,0,0,0,0,<NA>,0,12042800.0,106.0
4999,5000,花園町民宿,民宿,北海道,北見市,花園町,090-0816,5000,2.596053,0,...,0,0,0,0,0,<NA>,1,0,1645000.0,92.0

In [45]:
(
    pl_hotel
    #（2）hotel_id列をキーとして（1）の集計結果を左外部結合
    .join(
        #（1）予約履歴から条件抽出し、ホテル毎に集約
        pl_reservation
        .filter(pl.col("status") != "canceled")
        .filter(pl.col("checkout_date").dt.year() == 2019)
        .group_by("hotel_id")
        .agg([pl.col("total_price").sum(), pl.len()]),
        on="hotel_id", how="left"
    )
    #（3）結合されなかった行の数値を0埋め
    .with_columns(
        total_price=pl.col("total_price").fill_null(0),
        len=pl.col("len").fill_null(0)
    )
)

shape: (5_000, 41)
┌──────────┬──────────────┬──────────────┬─────────────┬───┬─────────┬─────────┬─────────────┬─────┐
│ hotel_id ┆ hotel_name   ┆ hotel_type   ┆ address_pre ┆ … ┆ tag_029 ┆ tag_030 ┆ total_price ┆ len │
│ ---      ┆ ---          ┆ ---          ┆ fecture     ┆   ┆ ---     ┆ ---     ┆ ---         ┆ --- │
│ i64      ┆ str          ┆ str          ┆ ---         ┆   ┆ i64     ┆ i64     ┆ i64         ┆ u32 │
│          ┆              ┆              ┆ str         ┆   ┆         ┆         ┆             ┆     │
╞══════════╪══════════════╪══════════════╪═════════════╪═══╪═════════╪═════════╪═════════════╪═════╡
│ 1        ┆ 北飯岡ホテル ┆ ビジネスホテ ┆ 岩手県      ┆ … ┆ 0       ┆ 0       ┆ 3017900     ┆ 83  │
│          ┆              ┆ ル           ┆             ┆   ┆         ┆         ┆             ┆     │
│ 2        ┆ 西二条南温泉 ┆ リゾートホテ ┆ 北海道      ┆ … ┆ 0       ┆ 0       ┆ 0           ┆ 0   │
│          ┆ ホテル       ┆ ル           ┆             ┆   ┆         ┆         ┆             ┆     │
│ 3        ┆ 小屋敷ペンシ ┆ 民宿         ┆ 青森県      ┆ … ┆ 0       ┆ 0       ┆ 10248600    ┆ 143 │
│          ┆ ョン         ┆              ┆             ┆   ┆         ┆         ┆             ┆     │
│ 4        ┆ 中後町民宿   ┆ 民宿         ┆ 愛知県      ┆ … ┆ 1       ┆ 0       ┆ 1808100     ┆ 94  │
│ 5        ┆ 鵜沼台ホテル ┆ ビジネスホテ ┆ 岐阜県      ┆ … ┆ 0       ┆ 0       ┆ 2421000     ┆ 73  │
│          ┆              ┆ ル           ┆             ┆   ┆         ┆         ┆             ┆     │
│ …        ┆ …            ┆ …            ┆ …           ┆ … ┆ …       ┆ …       ┆ …           ┆ …   │
│ 4996     ┆ 田辺通旅館   ┆ 旅館         ┆ 愛知県      ┆ … ┆ 1       ┆ 0       ┆ 6957500     ┆ 136 │
│ 4997     ┆ 六本木温泉旅 ┆ 旅館         ┆ 東京都      ┆ … ┆ 0       ┆ 0       ┆ 1663200     ┆ 57  │
│          ┆ 館           ┆              ┆             ┆   ┆         ┆         ┆             ┆     │
│ 4998     ┆ 丸山吉野町温 ┆ 旅館         ┆ 福岡県      ┆ … ┆ null    ┆ 1       ┆ 5275200     ┆ 81  │
│          ┆ 泉旅館       ┆              ┆             ┆   ┆         ┆         ┆             ┆     │
│ 4999     ┆ 神埼郡吉野ヶ ┆ ビジネスホテ ┆ 佐賀県      ┆ … ┆ null    ┆ 0       ┆ 12042800    ┆ 106 │
│          ┆ 里町ビジネス ┆ ル           ┆             ┆   ┆         ┆         ┆             ┆     │
│          ┆ ホテル       ┆              ┆             ┆   ┆         ┆         ┆             ┆     │
│ 5000     ┆ 花園町民宿   ┆ 民宿         ┆ 北海道      ┆ … ┆ 1       ┆ 0       ┆ 1645000     ┆ 92  │
└──────────┴──────────────┴──────────────┴─────────────┴───┴─────────┴─────────┴─────────────┴─────┘

In [46]:
(
    pd_hotel
    #（1）hotel_id列を結合キーとしてpd_reservationを左外部結合
    .merge(pd_reservation, on="hotel_id", how="left")
    #（2）未キャンセルかつcheckout_dateの年が2019の行のみ抽出
    .query("status != 'canceled'")
    .query("checkout_date.dt.year == 2019")
    #（3）集計結果以外に結果に残す列を全て結合キーに指定してgroup by
    .groupby([
        "hotel_id","hotel_name","hotel_type","address_prefecture",
        "address_city","address_town","address_zipcode","unit_price",
        "user_rating"
    ])
    .total_price.agg(["sum", "size"])
)

,,,,,,,,,sum,size
hotel_id,hotel_name,hotel_type,address_prefecture,address_city,address_town,address_zipcode,unit_price,user_rating,,
1,北飯岡ホテル,ビジネスホテル,岩手県,盛岡市,北飯岡,020-0857,10300,3.256591,3017900.0,83
3,小屋敷ペンション,民宿,青森県,黒石市,小屋敷,036-0511,18600,1.381796,10248600.0,143
4,中後町民宿,民宿,愛知県,碧南市,中後町,447-0042,4900,2.090353,1808100.0,94
5,鵜沼台ホテル,ビジネスホテル,岐阜県,各務原市,鵜沼台,509-0121,9000,2.771490,2421000.0,73
6,新町ホテル,ビジネスホテル,熊本県,宇土市,新町,869-0444,6600,4.116585,3128400.0,102
...,...,...,...,...,...,...,...,...,...,...
4994,樋瀬戸民宿,民宿,富山県,南砺市,樋瀬戸,939-1763,8600,4.348467,3293800.0,85
4995,西品川民宿,民宿,東京都,品川区,西品川,141-0033,4400,3.505784,462000.0,29
4997,六本木温泉旅館,旅館,東京都,港区,六本木,106-8544,8800,1.499441,1663200.0,57
4998,丸山吉野町温泉旅館,旅館,福岡県,北九州市門司区,丸山吉野町,801-0824,15700,2.336651,5275200.0,81
5000,花園町民宿,民宿,北海道,北見市,花園町,090-0816,5000,2.596053,1645000.0,92

In [47]:
import numpy as np

(
    pd_customer
    #（4）pd_customerに（1）〜（3）の集計結果を左外部結合
    .merge(
        pd_reservation
        #（1）pd_reservationにpd_hotelを左外部結合
        .merge(pd_hotel[["hotel_id", "hotel_type"]], on="hotel_id", how="left")
        #（2）ホテル種別ごとのデータ数カウント用の列を作成
        .assign(
            ryokan_cnt=lambda df: np.where(df.hotel_type == "旅館", 1, 0),
            resort_hotel_cnt=lambda df:
                np.where(df.hotel_type == "リゾートホテル", 1, 0),
            business_hotel_cnt=lambda df:
                np.where(df.hotel_type == "ビジネスホテル", 1, 0),
            minsyuku_cnt=lambda df: np.where(df.hotel_type == "民宿", 1, 0)
        )
        #（3）customer_idごとにホテル種別ごとのデータ数をカウント
        .groupby("customer_id")[["ryokan_cnt", "resort_hotel_cnt",
                                "business_hotel_cnt", "minsyuku_cnt"]].sum(),
        on="customer_id", how="left"
    )
    #（5）結合されなかった行の数値を0埋め
    .fillna({"ryokan_cnt": 0, "resort_hotel_cnt": 0,
            "business_hotel_cnt": 0, "minsyuku_cnt": 0})
)

,customer_id,name,age,sex,address_prefecture,address_city,address_town,address_zipcode,ryokan_cnt,resort_hotel_cnt,business_hotel_cnt,minsyuku_cnt
0,1,山田 裕太,75,<NA>,岐阜県,岐阜市,鷺山清洲町,502-0853,1.0,0.0,1.0,4.0
1,2,藤井 稔,83,M,大阪府,豊能郡能勢町,地黄,563-0121,1.0,1.0,1.0,3.0
2,3,青木 太一,62,M,佐賀県,佐賀市,本庄町袋,840-0023,2.0,2.0,0.0,3.0
3,4,渡辺 裕太,28,M,福島県,喜多方市,豊川町高堂太,966-0911,1.0,0.0,2.0,1.0
4,5,渡辺 明美,62,F,兵庫県,西宮市,津門西口町,663-8231,2.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
499995,499996,高橋 洋介,26,M,山形県,山形市,下東山,990-2232,1.0,0.0,1.0,2.0
499996,499997,山口 治,42,M,岩手県,一関市,室根町津谷川,029-1211,0.0,0.0,1.0,2.0
499997,499998,石井 拓真,39,M,山形県,山形市,桜ケ丘,990-2376,0.0,0.0,0.0,1.0
499998,499999,坂本 くみ子,66,F,群馬県,富岡市,曽木,370-2315,3.0,0.0,1.0,0.0
499999,500000,前田 聡太郎,49,<NA>,兵庫県,姫路市,広畑区西夢前台,671-1103,1.0,2.0,2.0,0.0

In [48]:
(
    pl_customer
    #（3）pl_customerに（1）〜（2）の集計結果を左外部結合
    .join(
        pl_reservation
        #（1）pl_reservationにpl_hotelを左外部結合
        .join(pl_hotel.select(["hotel_id", "hotel_type"]), on="hotel_id", how="left")
        #（2）customer_idごとにホテル種別ごとのデータ数をカウント
        .group_by("customer_id").agg([
            pl.col("reservation_id").filter(pl.col("hotel_type") == "旅館")
                .len().alias("ryokan_cnt"),
            pl.col("reservation_id").filter(pl.col("hotel_type") == "リゾートホテル")
                .len().alias("resort_hotel_cnt"),
            pl.col("reservation_id").filter(pl.col("hotel_type") == "ビジネスホテル")
                .len().alias("business_hotel_cnt"),
            pl.col("reservation_id").filter(pl.col("hotel_type") == "民宿")
                .len().alias("minsyuku_cnt")
        ]),
        on="customer_id", how="left"
    )
    #（4）結合されなかった行の数値を0埋め
    .with_columns(
        ryokan_cnt=pl.col("ryokan_cnt").fill_null(0),
        resort_hotel_cnt=pl.col("resort_hotel_cnt").fill_null(0),
        business_hotel_cnt=pl.col("business_hotel_cnt").fill_null(0),
        minsyuku_cnt=pl.col("minsyuku_cnt").fill_null(0)
    )
)

shape: (500_000, 12)
┌─────────────┬─────────────┬─────┬──────┬───┬────────────┬─────────────┬─────────────┬────────────┐
│ customer_id ┆ name        ┆ age ┆ sex  ┆ … ┆ ryokan_cnt ┆ resort_hote ┆ business_ho ┆ minsyuku_c │
│ ---         ┆ ---         ┆ --- ┆ ---  ┆   ┆ ---        ┆ l_cnt       ┆ tel_cnt     ┆ nt         │
│ i64         ┆ str         ┆ i64 ┆ str  ┆   ┆ u32        ┆ ---         ┆ ---         ┆ ---        │
│             ┆             ┆     ┆      ┆   ┆            ┆ u32         ┆ u32         ┆ u32        │
╞═════════════╪═════════════╪═════╪══════╪═══╪════════════╪═════════════╪═════════════╪════════════╡
│ 1           ┆ 山田 裕太   ┆ 75  ┆ null ┆ … ┆ 1          ┆ 0           ┆ 1           ┆ 4          │
│ 2           ┆ 藤井 稔     ┆ 83  ┆ M    ┆ … ┆ 1          ┆ 1           ┆ 1           ┆ 3          │
│ 3           ┆ 青木 太一   ┆ 62  ┆ M    ┆ … ┆ 2          ┆ 2           ┆ 0           ┆ 3          │
│ 4           ┆ 渡辺 裕太   ┆ 28  ┆ M    ┆ … ┆ 1          ┆ 0           ┆ 2           ┆ 1          │
│ 5           ┆ 渡辺 明美   ┆ 62  ┆ F    ┆ … ┆ 2          ┆ 1           ┆ 0           ┆ 1          │
│ …           ┆ …           ┆ …   ┆ …    ┆ … ┆ …          ┆ …           ┆ …           ┆ …          │
│ 499996      ┆ 高橋 洋介   ┆ 26  ┆ M    ┆ … ┆ 1          ┆ 0           ┆ 1           ┆ 2          │
│ 499997      ┆ 山口 治     ┆ 42  ┆ M    ┆ … ┆ 0          ┆ 0           ┆ 1           ┆ 2          │
│ 499998      ┆ 石井 拓真   ┆ 39  ┆ M    ┆ … ┆ 0          ┆ 0           ┆ 0           ┆ 1          │
│ 499999      ┆ 坂本 くみ子 ┆ 66  ┆ F    ┆ … ┆ 3          ┆ 0           ┆ 1           ┆ 0          │
│ 500000      ┆ 前田 聡太郎 ┆ 49  ┆ null ┆ … ┆ 1          ┆ 2           ┆ 2           ┆ 0          │
└─────────────┴─────────────┴─────┴──────┴───┴────────────┴─────────────┴─────────────┴────────────┘

In [49]:
(
    pd_reservation
    #（1）未キャンセル、2019年チェックアウトを抽出
    .query("status != 'canceled'")
    .query("checkout_date.dt.year == 2019")
    #（2）checkout_dateを月周期のPeriod型に変換
    .assign(month=lambda df: df.checkout_date.dt.to_period("M"))
    #（3）顧客と月ごとに売上を集計
    .groupby(["customer_id", "month"])
    .total_price.sum()
)

/var/folders/57/jbbs3zzs09vd02vtg2w0vyg40000gn/T/ipykernel_2148/1727064503.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  .assign(month=lambda df: df.checkout_date.dt.to_period("M"))

customer_id  month
2            2019-01     19200
4            2019-08     51300
             2019-09     22500
5            2019-07      8500
7            2019-01     51600
                         ...
499991       2019-11     34000
             2019-12     44400
499992       2019-08    301500
             2019-09     81000
500000       2019-01    126600
Name: total_price, Length: 341327, dtype: int64

In [50]:
(
    pd_customer[["customer_id"]]
    #（1）顧客マスタに月の時系列をクロス結合し、顧客毎の時系列フレームを生成
    .merge(
        pd.period_range("2019-01", "2019-12", freq="M")
        .to_series(name="month"), how="cross"
    )
    #（2）フレームに対して集計結果を左外部結合
    .merge(
        pd_reservation
        .query("status != 'canceled'")
        .assign(month=lambda df: df.checkout_date.dt.to_period("M"))
        .groupby(["customer_id", "month"])
        .total_price.sum(),
        on=["customer_id", "month"], how="left"
    )
    #（3）結合されなかった行の数値を0埋め
    .fillna({"total_price": 0})
)

/var/folders/57/jbbs3zzs09vd02vtg2w0vyg40000gn/T/ipykernel_2148/4089696254.py:12: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  .assign(month=lambda df: df.checkout_date.dt.to_period("M"))

         customer_id    month  total_price
0                  1  2019-01          0.0
1                  1  2019-02          0.0
2                  1  2019-03          0.0
3                  1  2019-04          0.0
4                  1  2019-05          0.0
...              ...      ...          ...
5999995       500000  2019-08          0.0
5999996       500000  2019-09          0.0
5999997       500000  2019-10          0.0
5999998       500000  2019-11          0.0
5999999       500000  2019-12          0.0

[6000000 rows x 3 columns]

In [51]:
from datetime import date
(
    pl_customer.select("customer_id")
    #（1）顧客マスタに月の時系列をクロス結合し、顧客毎の時系列フレームを生成
    .join(
        pl.date_range(date(2019,1,1), date(2019,12,1), "1mo", eager=True)
        .alias("month").to_frame(), how="cross"
    )
    #（2）フレームに対して集計結果を左外部結合
    .join(
        pl_reservation
        .filter(pl.col("status") != "canceled")
        .group_by([
            "customer_id",
            pl.col("checkout_date").dt.truncate("1mo").dt.date().alias("month")
        ])
        .agg(pl.col("total_price").sum()),
        on=["customer_id", "month"], how="left"
    )
    #（3）結合されなかった行の数値を0埋め
    .with_columns(pl.col("total_price").fill_null(0))
)

shape: (6_000_000, 3)
┌─────────────┬────────────┬─────────────┐
│ customer_id ┆ month      ┆ total_price │
│ ---         ┆ ---        ┆ ---         │
│ i64         ┆ date       ┆ i64         │
╞═════════════╪════════════╪═════════════╡
│ 1           ┆ 2019-01-01 ┆ 0           │
│ 1           ┆ 2019-02-01 ┆ 0           │
│ 1           ┆ 2019-03-01 ┆ 0           │
│ 1           ┆ 2019-04-01 ┆ 0           │
│ 1           ┆ 2019-05-01 ┆ 0           │
│ …           ┆ …          ┆ …           │
│ 500000      ┆ 2019-08-01 ┆ 0           │
│ 500000      ┆ 2019-09-01 ┆ 0           │
│ 500000      ┆ 2019-10-01 ┆ 0           │
│ 500000      ┆ 2019-11-01 ┆ 0           │
│ 500000      ┆ 2019-12-01 ┆ 0           │
└─────────────┴────────────┴─────────────┘

In [52]:
(
    pd_reservation
    #（1）reserved_atを日付単位に丸めたreserve_date列を作成
    .assign(reserve_date=lambda df: df.reserved_at.dt.normalize())
    #（4）reserve_dateを結合キーとしてキャンペーンマスタと結合
    .merge(
        pd_campaign
        #（2）starts_atとends_atの間の日付単位の時系列を作成
        .assign(
            reserve_date=lambda df: df.apply(
                lambda r: pd.date_range(r.starts_at, r.ends_at),
                axis=1
            )
        )[["campaign_name", "reserve_date"]]
        #（3）日付の時系列を複数行に展開
        .explode("reserve_date"),
        on="reserve_date", how="left"
    )
    #（5）不要な列を削除
    .drop(columns="reserve_date")
)

NameError: name 'pd_campaign' is not defined

In [ ]:
(
    pl_reservation
    #（1）reserved_atを日付単位に丸めたreserve_date列を作成
    .with_columns(reserve_date=pl.col("reserved_at").dt.date())
    #（4）reserve_dateを結合キーとしてキャンペーンマスタと結合
    .join(
        pl_campaign
        #（2）starts_atとends_atの間の日付単位の時系列を作成
        .select([
            pl.date_ranges(
                pl.col("starts_at").dt.date(),
                pl.col("ends_at").dt.date(), "1d"
            )
            .alias("reserve_date"),
            pl.col("campaign_name")
        ])
        #（3）日付の時系列を複数行に展開
        .explode("reserve_date"),
        on="reserve_date", how="left"
    )
    #（5）不要な列を削除
    .drop("reserve_date")
)

shape: (2_000_000, 12)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ reservatio ┆ hotel_id ┆ customer_ ┆ reserved_ ┆ … ┆ total_pri ┆ status   ┆ canceled_ ┆ campaign_ │
│ n_id       ┆ ---      ┆ id        ┆ at        ┆   ┆ ce        ┆ ---      ┆ at        ┆ name      │
│ ---        ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str      ┆ ---       ┆ ---       │
│ i64        ┆          ┆ i64       ┆ datetime[ ┆   ┆ i64       ┆          ┆ datetime[ ┆ str       │
│            ┆          ┆           ┆ ns, Asia/ ┆   ┆           ┆          ┆ ns, Asia/ ┆           │
│            ┆          ┆           ┆ Tokyo]    ┆   ┆           ┆          ┆ Tokyo]    ┆           │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 1          ┆ 2460     ┆ 53431     ┆ 2013-12-3 ┆ … ┆ 37800     ┆ reserved ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 07:00:14  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 2          ┆ 962      ┆ 488390    ┆ 2013-12-3 ┆ … ┆ 42000     ┆ reserved ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 08:23:35  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 3          ┆ 558      ┆ 341335    ┆ 2013-12-3 ┆ … ┆ 20400     ┆ reserved ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 09:02:05  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 4          ┆ 3666     ┆ 398981    ┆ 2013-12-3 ┆ … ┆ 39600     ┆ reserved ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 23:44:54  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 5          ┆ 2180     ┆ 220381    ┆ 2014-01-0 ┆ … ┆ 16500     ┆ reserved ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 02:47:50  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ …          ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ 1999996    ┆ 2357     ┆ 280303    ┆ 2019-12-2 ┆ … ┆ 26000     ┆ reserved ┆ null      ┆ 冬休みキ  │
│            ┆          ┆           ┆ 7         ┆   ┆           ┆          ┆           ┆ ャンペー  │
│            ┆          ┆           ┆ 12:14:07  ┆   ┆           ┆          ┆           ┆ ン        │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 1999997    ┆ 319      ┆ 499387    ┆ 2019-12-2 ┆ … ┆ 7100      ┆ canceled ┆ 2019-12-2 ┆ 冬休みキ  │
│            ┆          ┆           ┆ 7         ┆   ┆           ┆          ┆ 8         ┆ ャンペー  │
│            ┆          ┆           ┆ 14:08:57  ┆   ┆           ┆          ┆ 21:37:30  ┆ ン        │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆ JST       ┆           │
│ 1999998    ┆ 2834     ┆ 461799    ┆ 2019-12-2 ┆ … ┆ 105000    ┆ reserved ┆ null      ┆ 冬休みキ  │
│            ┆          ┆           ┆ 8         ┆   ┆           ┆          ┆           ┆ ャンペー  │
│            ┆          ┆           ┆ 04:59:51  ┆   ┆           ┆          ┆           ┆ ン        │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 1999999    ┆ 3643     ┆ 163568    ┆ 2019-12-2 ┆ … ┆ 17000     ┆ reserved ┆ null      ┆ 冬休みキ  │
│            ┆          ┆           ┆ 8         ┆   ┆           ┆          ┆           ┆ ャンペー  │
│            ┆          ┆           ┆ 11:56:19  ┆   ┆           ┆          ┆           ┆ ン        │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 2000000    ┆ 820      ┆ 449765    ┆ 2019-12-2 ┆ … ┆ 7800      ┆ reserved ┆ null      ┆ 冬休みキ  │
│            ┆          ┆           ┆ 8         ┆   ┆           ┆          ┆           ┆ ャンペー  │
│            ┆          ┆           ┆ 17:20:08  ┆   ┆           ┆          ┆           ┆ ン        │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [ ]:
print(pd_campaign.head().to_markdown(index=False))

| campaign_name        | starts_at                 | ends_at                   |
|:---------------------|:--------------------------|:--------------------------|
| 初売りキャンペーン   | 2015-01-01 00:00:00+09:00 | 2015-01-14 23:59:59+09:00 |
| 春休みキャンペーン   | 2015-02-01 00:00:00+09:00 | 2015-03-20 23:59:59+09:00 |
| GWキャンペーン       | 2015-04-01 00:00:00+09:00 | 2015-04-30 23:59:59+09:00 |
| 夏休みキャンペーン   | 2015-07-01 00:00:00+09:00 | 2015-08-20 23:59:59+09:00 |
| オータムキャンペーン | 2015-09-01 00:00:00+09:00 | 2015-10-20 23:59:59+09:00 |

In [ ]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(
    pd_reservation, test_size=0.2, shuffle=True, random_state=71
)

In [ ]:
from sklearn.model_selection import KFold

# （1）交差検証用のデータ分割方法を定義
fold = KFold(n_splits=5, shuffle=True, random_state=71)

# （2）分割数分の繰り返し処理
for train_cv_no, test_cv_no in fold.split(pd_reservation):
    train_cv = pd_reservation.iloc[train_cv_no]
    test_cv = pd_reservation.iloc[test_cv_no]

    # ここに機械学習モデルの学習、検証処理を書く

# ここに交差検証の結果をまとめる処理を書く

In [ ]:
from sklearn.model_selection import TimeSeriesSplit
up

# （1）train_dataに予約日時を月単位に丸めた列を追加
train_data = pd_reservation.assign(reserved_ym=lambda df: df.reserved_at.dt.to_period('M').dt.to_timestamp())

# （2）月単位の時系列を作成
ts = pd.date_range(start="2014-01-01", end="2019-12-31", freq="MS")

# （3）交差検証用のデータ分割方法を定義
fold = TimeSeriesSplit(n_splits=4, max_train_size=24, test_size=12)

# （4）分割数分の繰り返し処理
for train_cv_no, test_cv_no in fold.split(ts):
    train_cv = train_data.loc[lambda df: df.reserved_ym.between(ts[train_cv_no[0]], ts[train_cv_no[-1]])]
    test_cv = train_data.loc[lambda df: df.reserved_ym.between(ts[test_cv_no[0]], ts[test_cv_no[-1]])]
    # ここに機械学習モデルの学習、検証処理を書く

# ここに交差検証の結果をまとめる処理を書く

/var/folders/57/jbbs3zzs09vd02vtg2w0vyg40000gn/T/ipykernel_65125/3719256471.py:4: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  train_data = pd_reservation.assign(reserved_ym=lambda df: df.reserved_at.dt.to_period('M').dt.to_timestamp())

2014-01-01 02:47:50+09:00 2015-12-31 23:59:08+09:00
2016-01-01 00:00:25+09:00 2016-12-31 23:59:29+09:00

2015-01-01 00:01:39+09:00 2016-12-31 23:59:29+09:00
2017-01-01 00:00:18+09:00 2017-12-31 23:58:58+09:00

2016-01-01 00:00:25+09:00 2017-12-31 23:58:58+09:00
2018-01-01 00:00:31+09:00 2018-12-31 23:59:58+09:00

2017-01-01 00:00:18+09:00 2018-12-31 23:59:58+09:00
2019-01-01 00:00:44+09:00 2019-12-28 17:20:08+09:00

In [ ]:
from sklearn.model_selection import GroupKFold

# （1）交差検証用のデータ分割方法を定義
fold = GroupKFold(n_splits=5)

# （2）分割数分の繰り返し処理
for train_cv_no, test_cv_no in fold.split(pd_reservation, groups=pd_reservation.hotel_id):
    train_cv = pd_reservation.iloc[train_cv_no]
    test_cv = pd_reservation.iloc[test_cv_no]

    # ここにモデルの学習、検証処理を書く

# ここに交差検証の結果をまとめる処理を書く

In [ ]:
from sklearn.model_selection import KFold

# （1）グループのユニーク値のリストを作成
groups = pd_reservation["hotel_id"].unique()

# （2）交差検証用のデータ分割方法を定義
fold = KFold(n_splits=5, shuffle=True, random_state=71)

# （3）分割数分の繰り返し処理
for train_cv_no, test_cv_no in fold.split(groups):
    train_cv = pd_reservation.loc[lambda df: df.hotel_id.isin(groups[train_cv_no])]
    test_cv = pd_reservation.loc[lambda df: df.hotel_id.isin(groups[test_cv_no])]

    # ここにモデルの学習、検証処理を書く

# ここに交差検証の結果をまとめる処理を書く

In [ ]:
from imblearn.under_sampling import RandomUnderSampler

# （1）学習データの特徴量と目的変数を分割
feature_cols = ["length_of_stay", "people_num", "total_price"]
target_col = "status"
X = pd_reservation[feature_cols]
y = pd_reservation[target_col]

# （2）アンダーサンプリングを行うクラスのオブジェクトを作成
sampler = RandomUnderSampler(random_state=71)

# （3）特徴量と目的変数を関数に渡し、アンダーサンプリングを実行
X_sampled, y_sampled = sampler.fit_resample(X, y)

In [ ]:
y.value_counts()

status
reserved    1799589
canceled     200411
Name: count, dtype: int64

In [ ]:
y_sampled.value_counts()

status
canceled    200411
reserved    200411
Name: count, dtype: int64

In [ ]:
from imblearn.over_sampling import RandomOverSampler

# （1）学習データの特徴量と目的変数を分割
feature_cols = ["length_of_stay", "people_num", "total_price"]
target_col = "status"
X = pd_reservation[feature_cols]
y = pd_reservation[target_col]

# （2）オーバーサンプリングを行うクラスのオブジェクトを作成
sampler = RandomOverSampler(random_state=71)

# （3）特徴量と目的変数を関数に渡し、オーバーサンプリングを実行
X_sampled, y_sampled = sampler.fit_resample(X, y)

In [ ]:
y_sampled.value_counts()

status
reserved    1799589
canceled    1799589
Name: count, dtype: int64

In [ ]:
from imblearn.ensemble import BalancedBaggingClassifier
from sklearn.tree import DecisionTreeClassifier

# （1）学習データの特徴量と目的変数を分割
feature_cols = ["length_of_stay", "people_num", "total_price"]
target_col = "status"
X = pd_reservation[feature_cols]
y = pd_reservation[target_col]

# （2）予測モデル、およびアンダーサンプリング+バギングを行うクラスのオブジェクトを作成
classifer = DecisionTreeClassifier()
model = BalancedBaggingClassifier(estimator=classifer, random_state=71)
# （3）特徴量と目的変数を関数に渡し、学習を実行
model.fit(X, y)

BalancedBaggingClassifier(estimator=DecisionTreeClassifier(), random_state=71)

In [ ]:
(
    pd_reservation
    .sort_values("reserved_at")
    .assign(
        total_price_at_prev=lambda df: df.groupby("customer_id").total_price.shift(1),
        total_price_at_2prev=lambda df: df.groupby("customer_id").total_price.shift(2)
    )
)

,reservation_id,hotel_id,customer_id,reserved_at,checkin_date,checkout_date,length_of_stay,people_num,total_price,status,canceled_at,total_price_at_prev,total_price_at_2prev
0,1,2460,53431,2013-12-31 07:00:14+09:00,2014-12-31 00:00:00+09:00,2015-01-03 00:00:00+09:00,3,2,37800,reserved,NaT,NaN,NaN
1,2,962,488390,2013-12-31 08:23:35+09:00,2014-12-31 00:00:00+09:00,2015-01-02 00:00:00+09:00,2,3,42000,reserved,NaT,NaN,NaN
2,3,558,341335,2013-12-31 09:02:05+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,2,20400,reserved,NaT,NaN,NaN
3,4,3666,398981,2013-12-31 23:44:54+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,4,39600,reserved,NaT,NaN,NaN
4,5,2180,220381,2014-01-01 02:47:50+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,3,16500,reserved,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999995,1999996,2357,280303,2019-12-27 12:14:07+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,4,26000,reserved,NaT,23700.0,21000.0
1999996,1999997,319,499387,2019-12-27 14:08:57+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,1,7100,canceled,2019-12-28 21:37:30+09:00,NaN,NaN
1999997,1999998,2834,461799,2019-12-28 04:59:51+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,5,105000,reserved,NaT,27800.0,17200.0
1999998,1999999,3643,163568,2019-12-28 11:56:19+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,1,17000,reserved,NaT,31800.0,64800.0
1999999,2000000,820,449765,2019-12-28 17:20:08+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,1,7800,reserved,NaT,32100.0,10600.0

In [ ]:
(
    pl_reservation
    .sort("reserved_at")
    .with_columns(
        total_price_at_prev=
            pl.col("total_price").shift(1).over("customer_id"),
        total_price_at_2prev=
            pl.col("total_price").shift(2).over("customer_id")
    )
)

shape: (2_000_000, 13)
┌────────────┬──────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ reservatio ┆ hotel_id ┆ customer_ ┆ reserved_ ┆ … ┆ status   ┆ canceled_ ┆ total_pri ┆ total_pri │
│ n_id       ┆ ---      ┆ id        ┆ at        ┆   ┆ ---      ┆ at        ┆ ce_at_pre ┆ ce_at_2pr │
│ ---        ┆ i64      ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ v         ┆ ev        │
│ i64        ┆          ┆ i64       ┆ datetime[ ┆   ┆          ┆ datetime[ ┆ ---       ┆ ---       │
│            ┆          ┆           ┆ ns, Asia/ ┆   ┆          ┆ ns, Asia/ ┆ i64       ┆ i64       │
│            ┆          ┆           ┆ Tokyo]    ┆   ┆          ┆ Tokyo]    ┆           ┆           │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 1          ┆ 2460     ┆ 53431     ┆ 2013-12-3 ┆ … ┆ reserved ┆ null      ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ 07:00:14  ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆          ┆           ┆           ┆           │
│ 2          ┆ 962      ┆ 488390    ┆ 2013-12-3 ┆ … ┆ reserved ┆ null      ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ 08:23:35  ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆          ┆           ┆           ┆           │
│ 3          ┆ 558      ┆ 341335    ┆ 2013-12-3 ┆ … ┆ reserved ┆ null      ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ 09:02:05  ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆          ┆           ┆           ┆           │
│ 4          ┆ 3666     ┆ 398981    ┆ 2013-12-3 ┆ … ┆ reserved ┆ null      ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ 23:44:54  ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆          ┆           ┆           ┆           │
│ 5          ┆ 2180     ┆ 220381    ┆ 2014-01-0 ┆ … ┆ reserved ┆ null      ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ 02:47:50  ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆          ┆           ┆           ┆           │
│ …          ┆ …        ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 1999996    ┆ 2357     ┆ 280303    ┆ 2019-12-2 ┆ … ┆ reserved ┆ null      ┆ 23700     ┆ 21000     │
│            ┆          ┆           ┆ 7         ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ 12:14:07  ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆          ┆           ┆           ┆           │
│ 1999997    ┆ 319      ┆ 499387    ┆ 2019-12-2 ┆ … ┆ canceled ┆ 2019-12-2 ┆ null      ┆ null      │
│            ┆          ┆           ┆ 7         ┆   ┆          ┆ 8         ┆           ┆           │
│            ┆          ┆           ┆ 14:08:57  ┆   ┆          ┆ 21:37:30  ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆          ┆ JST       ┆           ┆           │
│ 1999998    ┆ 2834     ┆ 461799    ┆ 2019-12-2 ┆ … ┆ reserved ┆ null      ┆ 27800     ┆ 17200     │
│            ┆          ┆           ┆ 8         ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ 04:59:51  ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆          ┆           ┆           ┆           │
│ 1999999    ┆ 3643     ┆ 163568    ┆ 2019-12-2 ┆ … ┆ reserved ┆ null      ┆ 31800     ┆ 64800     │
│            ┆          ┆           ┆ 8         ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ 11:56:19  ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆          ┆           ┆           ┆           │
│ 2000000    ┆ 820      ┆ 449765    ┆ 2019-12-2 ┆ … ┆ reserved ┆ null      ┆ 32100     ┆ 10600     │
│            ┆          ┆           ┆ 8         ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ 17:20:08  ┆   ┆          ┆           ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆          ┆           ┆           ┆           │
└────────────┴──────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [ ]:
(
    pd_reservation
    .sort_values("reserved_at")
    .assign(
        total_price_from_2prev_to_current=lambda df:
            df.groupby("customer_id").total_price.rolling(3, closed='left').sum().reset_index(level=0, drop=True)
    )
)

,reservation_id,hotel_id,customer_id,reserved_at,checkin_date,checkout_date,length_of_stay,people_num,total_price,status,canceled_at,total_price_from_2prev_to_current
0,1,2460,53431,2013-12-31 07:00:14+09:00,2014-12-31 00:00:00+09:00,2015-01-03 00:00:00+09:00,3,2,37800,reserved,NaT,NaN
1,2,962,488390,2013-12-31 08:23:35+09:00,2014-12-31 00:00:00+09:00,2015-01-02 00:00:00+09:00,2,3,42000,reserved,NaT,NaN
2,3,558,341335,2013-12-31 09:02:05+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,2,20400,reserved,NaT,NaN
3,4,3666,398981,2013-12-31 23:44:54+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,4,39600,reserved,NaT,NaN
4,5,2180,220381,2014-01-01 02:47:50+09:00,2014-12-31 00:00:00+09:00,2015-01-01 00:00:00+09:00,1,3,16500,reserved,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1999995,1999996,2357,280303,2019-12-27 12:14:07+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,4,26000,reserved,NaT,114300.0
1999996,1999997,319,499387,2019-12-27 14:08:57+09:00,2019-12-29 00:00:00+09:00,2019-12-30 00:00:00+09:00,1,1,7100,canceled,2019-12-28 21:37:30+09:00,NaN
1999997,1999998,2834,461799,2019-12-28 04:59:51+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,5,105000,reserved,NaT,84600.0
1999998,1999999,3643,163568,2019-12-28 11:56:19+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,1,17000,reserved,NaT,131600.0
1999999,2000000,820,449765,2019-12-28 17:20:08+09:00,2019-12-30 00:00:00+09:00,2019-12-31 00:00:00+09:00,1,1,7800,reserved,NaT,91700.0

In [ ]:
(
    pl_reservation
    .sort("reserved_at")
    .with_columns(
        total_price_from_2prev_to_current=pl.col("total_price").rolling_sum(3).shift(1).over("customer_id"),
    )
)

shape: (2_000_000, 12)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ reservatio ┆ hotel_id ┆ customer_ ┆ reserved_ ┆ … ┆ total_pri ┆ status   ┆ canceled_ ┆ total_pri │
│ n_id       ┆ ---      ┆ id        ┆ at        ┆   ┆ ce        ┆ ---      ┆ at        ┆ ce_from_2 │
│ ---        ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str      ┆ ---       ┆ prev_to_c │
│ i64        ┆          ┆ i64       ┆ datetime[ ┆   ┆ i64       ┆          ┆ datetime[ ┆ urr…      │
│            ┆          ┆           ┆ ns, Asia/ ┆   ┆           ┆          ┆ ns, Asia/ ┆ ---       │
│            ┆          ┆           ┆ Tokyo]    ┆   ┆           ┆          ┆ Tokyo]    ┆ i64       │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 1          ┆ 2460     ┆ 53431     ┆ 2013-12-3 ┆ … ┆ 37800     ┆ reserved ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 07:00:14  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 2          ┆ 962      ┆ 488390    ┆ 2013-12-3 ┆ … ┆ 42000     ┆ reserved ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 08:23:35  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 3          ┆ 558      ┆ 341335    ┆ 2013-12-3 ┆ … ┆ 20400     ┆ reserved ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 09:02:05  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 4          ┆ 3666     ┆ 398981    ┆ 2013-12-3 ┆ … ┆ 39600     ┆ reserved ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 23:44:54  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 5          ┆ 2180     ┆ 220381    ┆ 2014-01-0 ┆ … ┆ 16500     ┆ reserved ┆ null      ┆ null      │
│            ┆          ┆           ┆ 1         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 02:47:50  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ …          ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ 1999996    ┆ 2357     ┆ 280303    ┆ 2019-12-2 ┆ … ┆ 26000     ┆ reserved ┆ null      ┆ 114300    │
│            ┆          ┆           ┆ 7         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 12:14:07  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 1999997    ┆ 319      ┆ 499387    ┆ 2019-12-2 ┆ … ┆ 7100      ┆ canceled ┆ 2019-12-2 ┆ null      │
│            ┆          ┆           ┆ 7         ┆   ┆           ┆          ┆ 8         ┆           │
│            ┆          ┆           ┆ 14:08:57  ┆   ┆           ┆          ┆ 21:37:30  ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆ JST       ┆           │
│ 1999998    ┆ 2834     ┆ 461799    ┆ 2019-12-2 ┆ … ┆ 105000    ┆ reserved ┆ null      ┆ 84600     │
│            ┆          ┆           ┆ 8         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 04:59:51  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 1999999    ┆ 3643     ┆ 163568    ┆ 2019-12-2 ┆ … ┆ 17000     ┆ reserved ┆ null      ┆ 131600    │
│            ┆          ┆           ┆ 8         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 11:56:19  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
│ 2000000    ┆ 820      ┆ 449765    ┆ 2019-12-2 ┆ … ┆ 7800      ┆ reserved ┆ null      ┆ 91700     │
│            ┆          ┆           ┆ 8         ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ 17:20:08  ┆   ┆           ┆          ┆           ┆           │
│            ┆          ┆           ┆ JST       ┆   ┆           ┆          ┆           ┆           │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘